version: '3.9'

services:
  db:
    image: postgres:16.3
    restart: on-failure
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: andre
      POSTGRES_PASSWORD: andre
      POSTGRES_DB: spring_testing
    ports:
      - 5432:5432
    networks:
      - andre-lucs

  spring-rest-api:
    image: andre-lucs/spring-rest-api
    restart: on-failure
    ports:
      - 5050:80
    build: .
    working_dir: /
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/spring_testing
      SPRING.DATASOURCE.USERNAME: andre
      SPRING.DATASOURCE.PASSWORD: andre
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - andre-lucs

networks:
  andre-lucs:
    driver: bridge